### PR TITLE
chore: configure disarm, bump up service(6.0.10), env vars

### PR DESCRIPTION
**Pull request by VinneyJ**
Modifications to the stack:
1. Added nginx service configuration.
2. Bumped the service versions to 6.0.10.
3. Configure Elasticsearch Cluster URLs.
4. Added & configured the Disarm Framework.
5. Fixed the environment variables.
6. Configured docker swarm placements.

### CODE REVIEW

**Comment by kilemensi** [comment]
We have three PRs that are trying to do pretty much the same thing (at least from where i'm seating):
1. This one,
2. #1 (original one), and
3. #2 

I think you and @thepsalmist need to figure out which one needs to merged first, etc., so that the rest of the team can actually review the PRs in order.

**Comment by VinneyJ** [comment]
> We have three PRs that are trying to do pretty much the same thing (at least from where i'm seating):
> 
> 1. This one,
> 2. [Ft/deployment setup #1](https://github.com/CodeForAfrica/cfa-opencti-docker/pull/1) (original one), and
> 3. [chore: configure disarm, bump up service(6.0.10), env vars #2](https://github.com/CodeForAfrica/cfa-opencti-docker/pull/2)
> 
> I think you and @thepsalmist need to figure out which one needs to merged first, etc., so that the rest of the team can actually review the PRs in order.

Sure @kilemensi  we'll do that.

**Comment by thepsalmist** [comment]
@VinneyJ you can base your updated PR's to the `ft/deployment-setup` branch - original PR #1 to see the diff with the new PRs. I've asked for re-review, if we can get that merged then we should close the other two.

**Comment by VinneyJ** [comment]
> @VinneyJ you can base your updated PR's to the `ft/deployment-setup` branch - original PR #1 to see the diff with the new PRs. I've asked for re-review, if we can get that merged then we should close the other two.

Sounds good @thepsalmist.

**Pull request merged**
