### PR TITLE
chore: change swarm deploy restart polity

### PR DESCRIPTION
**Pull request by VinneyJ**
Changed the restart policy from `restart:always` to 
```  
deploy: 
    restart_policy:
    condition: on-failure
    delay: 3s
    max_attempts: 5
    window: 60s`
```
This is suitable for docker swarm deployment services.

### CODE REVIEW

**Comment by kilemensi** [comment]
Before even review this @VinneyJ, why do we need a completely new file (`docker-swarm-deploy-yml`)?

**Comment by VinneyJ** [comment]
No, we do not @kilemensi This is just for the team to see the potential changes. I did not want to modify the original yet. Once tested and the team is okay with what they see in the code, we can modify the original.

**Comment by kilemensi** [comment]
This is why you create a new git branch and commit your changes to that branch... changes in the new branch don't affect `main` branch @VinneyJ 


If it's a completely new file, it's 10 times harder to actually see where you propose to make changes.

**Comment by VinneyJ** [comment]
We have not yet approved and merged our previous changes. In that case, I will base my changes on #3. I hope that will be a bit better? @kilemensi

**Comment by kilemensi** [comment]
I think so @VinneyJ ... but why are the previous PRs still open?

**Pull request closed without merging**
